default:
  content:
    - name: "Use Python with R"
      path: "./rmarkdown-notebook"
      description: "Use the reticulate package to integrate Python into an R Markdown notebook."
      tag:
        - "Demo Content|Python"
      url: "/python/reticulate/"
      image: "reticulated_python.png"
    - name: "Image Classification with PyTorch"
      path: "./image-classifier"
      description: "An interactive Shiny app that uses R and Python to classify images into categories using a pretrained PyTorch model."
      tag:
        - "Demo Content|Python"
      url: "/python/image-classification/"
      image: "image-classifier/pytorch-logo.png"
