default:
  content:
    - name: "Use Python with R"
      path: "./reticulate"
      description: "Use the reticulate package to integrate Python into an R Markdown notebook."
      tag:
        - "Demo Content|Python"
      url: "/python/reticulate/"